package com.liyin.liger.sys.model;

// default package
// Generated 2017-7-15 11:28:57 by Hibernate Tools 4.0.0

/**
 * SysConfig generated by hbm2java
 */
public class SysConfig implements java.io.Serializable {

	private Long id;
	private String key;
	private String value;
	private Byte status;
	private String remark;

	public SysConfig() {
	}

	public SysConfig(String key, String value, Byte status, String remark) {
		this.key = key;
		this.value = value;
		this.status = status;
		this.remark = remark;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
