package com.liyin.liger.sys.model;

// default package
// Generated 2017-7-15 11:28:57 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SysLog generated by hbm2java
 */
public class SysLog implements java.io.Serializable {

	private Long id;
	private String username;
	private String operation;
	private String method;
	private String params;
	private String ip;
	private Date createDate;

	public SysLog() {
	}

	public SysLog(String username, String operation, String method,
			String params, String ip, Date createDate) {
		this.username = username;
		this.operation = operation;
		this.method = method;
		this.params = params;
		this.ip = ip;
		this.createDate = createDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
