package com.liyin.liger.sys.model;

// default package
// Generated 2017-7-15 11:28:57 by Hibernate Tools 4.0.0

/**
 * SysMenu generated by hbm2java
 */
public class SysMenu implements java.io.Serializable {

	private Long id;
	private Long parentId;
	private String name;
	private String url;
	private String perms;
	private Integer type;
	private String icon;
	private Integer orderNum;

	public SysMenu() {
	}

	public SysMenu(Long parentId, String name, String url, String perms,
			Integer type, String icon, Integer orderNum) {
		this.parentId = parentId;
		this.name = name;
		this.url = url;
		this.perms = perms;
		this.type = type;
		this.icon = icon;
		this.orderNum = orderNum;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	public String getPerms() {
		return this.perms;
	}

	public void setPerms(String perms) {
		this.perms = perms;
	}
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}
	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

}
