package com.liyin.liger.sys.model;

// default package
// Generated 2017-7-15 11:28:57 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SysRole generated by hbm2java
 */
public class SysRole implements java.io.Serializable {

	private Long roleId;
	private String roleName;
	private String remark;
	private Long createUserId;
	private Date createTime;

	public SysRole() {
	}

	public SysRole(String roleName, String remark, Long createUserId,
			Date createTime) {
		this.roleName = roleName;
		this.remark = remark;
		this.createUserId = createUserId;
		this.createTime = createTime;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	public Long getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
