package com.liyin.liger.sys.model;

// default package
// Generated 2017-7-15 11:28:57 by Hibernate Tools 4.0.0

/**
 * SysUserRole generated by hbm2java
 */
public class SysUserRole implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Long roleId;

	public SysUserRole() {
	}

	public SysUserRole(Long userId, Long roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

}
